language: node_js
dist: precise
node_js:
  - "6"
services:
  - mysql
env:
  - NODE_ENV=travis
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS retro98_test;'
  - npm install -g sequelize-cli
  - sequelize db:migrate
  - cd backend
install:
  - npm install
script:
  - npm test
after_script: NODE_ENV=travis istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
